webpack-and-babel - Marianne Cuevas
mariannecuevas/m3-0723-code-solutions pull request #1
Opened 2023-07-14 02:50 UTC by mariannecuevas

![Screenshot 2023-07-13 191640](https://github.com/mariannecuevas/m3-0723-code-solutions/assets/117552789/cff2e700-2045-4a50-93c7-e1a1e207fc4d)

2023-07-14 03:42 UTC, dseong0224 requested changes

2023-07-14 03:42 UTC, dseong0224 commented on webpack-and-babel/imports.js
> +import f2 from './foo';
you will need to access the file one level deeper than this

2023-07-17 04:14 UTC, mariannecuevas commented
I am not sure if I did this correctly
![image](https://github.com/mariannecuevas/m3-0723-code-solutions/assets/117552789/902f4fcb-ab62-4bd7-a571-7738f0848c9c)

2023-07-18 00:46 UTC, dseong0224 approved these changes

2023-07-18 01:06 UTC, merged